# Base configs
baseurl: "https://photography.starframe.org"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-M8LN7DEJRZ"

# UI configs
title: "Photography by Aarush"
subtitle: "See the world through my eyes!"
author: "Aarush P."
header:
 title: "Photography"
 subtitle: "by Aarush P."
footer:
 name: "Hey there, my name is Aarush"
 bio: "I'm a student at Georgia Tech, and I love improving on and mastering the art of photography."
 # github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork this repo on github</a> ;)"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
# social_urls:
#   twitter: "https://www.twitter.com/ram__patra"
#   instagram: "https://www.instagram.com/ram_patra"
#   dribbble: "https://dribbble.com/rampatra"
#   linkedin: "https://in.linkedin.com/in/ram-patra"
#   github: "https://www.github.com/rampatra"
